## 单个Azure实例的配置
azure:
  tenant_id: "your-tenant-id-here"
  client_id: "your-client-id-here"
  client_secret: "your-client-secret-here"
  subscription_id: "your-subscription-id-here"

defaults:
  resource_group: "your-resource-group" ##新建的资源组名称
  location: "your-location" ##新建IP所在的位置需要和保持机器位置一致，如：Korea Central 

## 你可以添加多个实例，每个实例对应一个Azure订阅
## 每个实例的配置包括租户ID、客户端ID、客户端密钥、订阅ID、资源组和位置
## 如果你只有一个Azure订阅，你可以添加一个默认实例
## 如果你有多个Azure订阅，你可以添加多个实例
instances:
  - name: "student-account"
    tenant_id: "your-student-tenant-id"
    client_id: "your-student-client-id"
    client_secret: "your-student-client-secret"
    subscription_id: "your-student-subscription-id"
    resource_group: "stu11"
    location: "koreacentral"

  - name: "production-account"
    tenant_id: "your-production-tenant-id"
    client_id: "your-production-client-id"
    client_secret: "your-production-client-secret"
    subscription_id: "your-production-subscription-id"
    resource_group: "prod-rg"
    location: "eastasia"

  - name: "test-account"
    tenant_id: "your-test-tenant-id"
    client_id: "your-test-client-id"
    client_secret: "your-test-client-secret"
    subscription_id: "your-test-subscription-id"
    resource_group: "test-rg"
    location: "southeastasia"